name: build-gallery

defaults:
  run:
    shell: bash

on:
  push:

jobs:
  build-gallery:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Build the gallery
      run: docker run -v $(pwd):/work thumbsupgallery/thumbsup thumbsup --no-usage-stats --input /work/images --output /work/gallery

    - name: Push the gallery
      run: |
        git config user.name github-actions-neocrym
        git config user.email github-actions@neocrym.com
        git add .
        git commit -m "generated"
        git push

